version: "3.8"

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./rapid_haul_be/.env
    ports:
      - "5434:5434"

  backend:
    build:
      context: ./rapid_haul_be
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./rapid_haul_be:/app
    ports:
      - "8000:8000"
    env_file:
      - ./rapid_haul_be/.env
    depends_on:
      - db
      - redis

  redis:
    image: "redis:latest"

  celery_worker:
    build:
      context: ./rapid_haul_be
      dockerfile: Dockerfile
    command:
      ["python", "-m", "celery", "-A", "rapid_haul_be", "worker", "-l", "INFO"]
    volumes:
      - ./rapid_haul_be:/app
    env_file:
      - ./rapid_haul_be/.env
    depends_on:
      - db
      - redis
      - backend

  frontend:
    build:
      context: ./rapid-haul-fe
      dockerfile: Dockerfile
      args:
        NODE_OPTIONS: "--max_old_space_size=4096"
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ./rapid-haul-fe:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./rapid-haul-fe/.env
    depends_on:
      - backend

volumes:
  postgres_data:
