# Generated by Django 5.1.3 on 2025-01-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="dot_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="insurance_provider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="policy_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="special_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="tax_id_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="dot_medical_card",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="endorsement",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="experience",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="experience_otr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="license_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="logbook_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="skills",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="special_skills",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="trailer_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
