# Generated by Django 5.1.3 on 2025-01-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_companyprofile_dot_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="selected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_drivers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
