# Generated by Django 5.1.3 on 2025-01-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_alter_driverprofile_selected_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="expiry_time",
            field=models.IntegerField(default=72),
        ),
    ]
