# Generated by Django 5.1.3 on 2025-01-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_driverprofile_expiry_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Occupied", "Occupied"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
