# Generated by Django 5.1.3 on 2025-01-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_driverprofile_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
