# Generated by Django 5.1.3 on 2025-01-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_driverprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="load_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="payment_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
