# Generated by Django 5.1.3 on 2025-01-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_companyprofile_company_name_companyprofile_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
